#!/bin/sh
##-==================================================-##
##   [+] FDroid-RepoList+GPGKeys.sh
##-==================================================-##
echo 
echo "[+]==========================================================================================[+]"
echo "     [+] FDroidMainRepo="https://f-droid.org/repo"                                              "
echo "[+]==========================================================================================[+]"
echo "     [+] GuardianProjectMainRepo="https://guardianproject.info/fdroid/repo"                     "
echo "     [+] export GuardianProjectMainRepo="https://guardianproject.info/fdroid/repo"              "
echo "[+]==========================================================================================[+]"
echo "     [+] GuardianProjectAWS="https://s3.amazonaws.com/guardianproject/fdroid/repo"              "
echo "     [+] export GuardianProjectAWS="https://s3.amazonaws.com/guardianproject/fdroid/repo"       "
echo "[+]==========================================================================================[+]"
echo "     [+] TorHiddenServiceFDroidRepo="http://bdf2wcxujkg6qqff.onion/fdroid/repo"                 "
echo "     [+] export TorHiddenServiceFDroidRepo="http://bdf2wcxujkg6qqff.onion/fdroid/repo"            "
echo "[+]==========================================================================================[+]"
echo "     [+] FDroidIOFrontend="https://f-droid.i2p.io/repo/"                                                  "
echo "     [+] export FDroidIOFrontend="https://f-droid.i2p.io/repo/"                                           "   
echo "[+]==========================================================================================[+]"
echo "     [+] F-DroidArchive="https://f-droid.org/archive"                                         "
echo "     [+] export F-DroidArchive="https://f-droid.org/archive"                                  "
echo "[+]==========================================================================================[+]"
echo "     [+] FDroidClientGitRepo="https://gitlab.com/fdroid/fdroidclient"                           "
echo "     [+] export FDroidClientGitRepo="https://gitlab.com/fdroid/fdroidclient"                    "
echo "[+]==========================================================================================[+]"
echo "##   [+] GPG signing key: "F-Droid <admin@f-droid.org>"                                         "
echo "[+]==========================================================================================[+]"
echo 
echo "## ------------------------------------------------------------------------------- ##"
echo "     [+] FDroidGPGFpr="37D2 C987 89D8 3119 4839 4E3E 41E7 044E 1DBA 2E89"            "
echo "     [+] FDroidGPGSubkeyFpr="802A 9799 0161 1234 6E1F EFF4 7A02 9E54 DD5D CE7A"      "
echo "## ------------------------------------------------------------------------------- ##"
echo 
echo "[+]=============================================================================================================[+]   "
echo "     [+] git tags signed by Daniel Martí <mvdan@mvdan.cc> aka Daniel Martí <mvdan@fsfe.org> with fingerprint:         "
echo "[+]=============================================================================================================[+]   "
echo "     [+] FDroidGitFpr="A9DA 13CD F7A1 4ACD D3DE E530 F4CA FFDB 4348 041C"                                             "
echo "[+]=============================================================================================================[+]   "
echo "##   [+] FDroidAPKSigningKey=                                                                                         "
echo "##                                                                                                                    "
echo "##   [+] Certificate fingerprints:                                                                                    "
echo "##       MD5:  17:C5:5C:62:80:56:E1:93:E9:56:44:E9:89:79:27:86                                                        "
echo "##       SHA1: 05:F2:E6:59:28:08:89:81:B3:17:FC:9A:6D:BF:E0:4B:0F:A1:3B:4E                                            "
echo "##       SHA256: 43:23:8D:51:2C:1E:5E:B2:D6:56:9F:4A:3A:FB:F5:52:34:18:B8:2E:0A:3E:D1:55:27:70:AB:B9:A9:C9:CC:AB      "
echo "[+]================================================================================================================[+]"
echo
echo "[+]===================================================================================[+]"
echo "                  [+] GPG signing key: F-Droid <admin@f-droid.org>                       "
echo "[+]===================================================================================[+]"
echo "## ----------------------------------------------------------------------------------- ##"
echo "##   [+] Primary key fingerprint: 37D2 C987 89D8 3119 4839 4E3E 41E7 044E 1DBA 2E89      "
echo "##   [+] Subkey fingerprint: 802A 9799 0161 1234 6E1F EFF4 7A02 9E54 DD5D CE7A           "
echo "## ----------------------------------------------------------------------------------- ##"
