#!/bin/bash
#: Title		: Show CAJA Variables
#: Date			: 2010-05-11
#: Author		: "John Lehr" <slo.sleuth@gmail.com>
#: Version		: 1.0
#: Description	: Shows Caja variable for selected items to aid in scripting

TEXT=$(echo -e "Selected File Paths: $CAJA_SCRIPT_SELECTED_FILE_PATHS\n\nSelected URI's: $CAJA_SCRIPT_SELECTED_URIS\n\nCurrent URI: $CAJA_SCRIPT_CURRENT_URI\n\nWindow Geometry: $CAJA_SCRIPT_WINDOW_GEOMETRY\n\nPositional Parameter \$\@: $@")

zenity --info \
	--title="Caja Variables" \
	--text="$TEXT"

exit 0
