

https://wiki.debian.org/SourcesList

https://cdimage.debian.org/debian-cd/current/amd64/jigdo-dvd/
https://www.debian.org/CD/verify
https://ftp-master.debian.org/keys.html
http://www.tldp.org/HOWTO/Debian-Jigdo/downloadingyourfirstimage.html


https://ftp-master.debian.org/keys/archive-key-7.0.asc
https://ftp-master.debian.org/keys/archive-key-8.asc
https://ftp-master.debian.org/keys/archive-key-8-security.asc
https://ftp-master.debian.org/keys/archive-key-9.asc
https://ftp-master.debian.org/keys/archive-key-9-security.asc





-{1,2,3,4,5,6,7,8,9,10}.jigdo




cp -v /etc/apt/sources.list /etc/apt/.sources.list.bak

echo "#deb http://archive.parrotsec.org/parrot parrot main contrib non-free" >> /etc/apt/sources.list
echo "#deb-src http://archive.parrotsec.org/parrot parrot main contrib non-free" >> /etc/apt/sources.list
echo -e "\n" >> /etc/apt/sources.list
echo "deb  http://deb.debian.org/debian stable main contrib non-free" >> /etc/apt/sources.list
echo "deb-src  http://deb.debian.org/debian stable main contrib non-free" >> /etc/apt/sources.list
echo -e "\n" >> /etc/apt/sources.list
echo "deb  http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list
echo "deb-src  http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list
echo -e "\n" >> /etc/apt/sources.list
echo "deb  http://deb.debian.org/debian stretch-updates main contrib non-free" >> /etc/apt/sources.list
echo "deb-src  http://deb.debian.org/debian stretch-updates main contrib non-free" >> /etc/apt/sources.list
echo -e "\n" >> /etc/apt/sources.list
echo "deb http://security.debian.org/ stretch/updates main contrib non-free" >> /etc/apt/sources.list
echo "deb-src http://security.debian.org/ stretch/updates main contrib non-free" >> /etc/apt/sources.list


export debianMirror='http://httpredir.debian.org/debian/'
export debianMirror='ftp://ftp.us.debian.org/debian/'


http://httpredir.debian.org/debian/
ftp://ftp.us.debian.org/debian/


http://mirrors.kernel.org/debian/
http://mirrors.ocf.berkeley.edu/debian/


sudo mkdir debian-files
cd debian-files/
sudo jigdo-lite




debianMirror='http://httpredir.debian.org/debian/'
jigdoDir="/where/you/keep/mirrors/debian-cd/current/jigdo"
imageDir=
templateDir=
tmpDir="/home/jigdo-mirror-tmpdir"
scanMenu='/var/cache/apt/archives/ /cdrom/'


git clone https://alioth.debian.org/anonscm/git/debian-cd/debian-cd.git



Jigsaw Download was created with the format of ISO9660 CD images in mind
jigdo actually fetches the individual files from the FTP server and
assembles them into an exact copy of your image (using `rolling checksum' concept')
jigdo downloads the parts and reassembles the image.

jigdo-file-cache.db is a Berekeley DB file containing md5sums of any files read in

The template file is a binary file generated by jigdo-file,
it contains information on how to reassemble the image

the script finishes by calculating a checksum of the generated image








echo " [+] "
gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x10460DAD76165AD81FBC0CE9988021A964E6EA7D
gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0xDF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0xF41D30342F3546695F65C66942468F4009EA8AC3

echo " [+] "
gpg --keyid-format 0xlong --import 'Debian CD signing key (6294BE9B).asc'
gpg --keyid-format 0xlong --import 'Debian CD signing key.asc'
gpg --keyid-format 0xlong --import 'Debian Testing CDs Automatic Signing Key.asc'

echo " [+] "
gpg --keyid-format 0xlong --fingerprint 0x10460DAD76165AD81FBC0CE9988021A964E6EA7D
gpg --keyid-format 0xlong --fingerprint 0xDF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg --keyid-format 0xlong --fingerprint 0xF41D30342F3546695F65C66942468F4009EA8AC3

echo " [+] "
Primary key fingerprint: F41D 3034 2F35 4669 5F65  C669 4246 8F40 09EA 8AC3
Primary key fingerprint: DF9B 9C49 EAA9 2984 3258  9D76 DA87 E80D 6294 BE9B
Primary key fingerprint: 1046 0DAD 7616 5AD8 1FBC  0CE9 9880 21A9 64E6 EA7D

echo " [+] "
gpg --lsign-key 0x10460DAD76165AD81FBC0CE9988021A964E6EA7D
gpg --lsign-key 0xDF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg --lsign-key 0xF41D30342F3546695F65C66942468F4009EA8AC3


sha256sum debian-9.2.1-amd64-DVD-4.iso
sha512sum debian-9.2.1-amd64-DVD-4.iso


gpg --keyid-format 0xlong --verify SHA256SUMS.sign SHA256SUMS
gpg --keyid-format 0xlong --verify SHA512SUMS.sign SHA512SUMS

cat SHA256SUMS
cat SHA512SUMS





f39358bf4093bdb21e94fdc6ba00a1acd59647cd52d63e3d0168f209e1ddd89b  debian-9.2.1-amd64-DVD-5.iso
f39358bf4093bdb21e94fdc6ba00a1acd59647cd52d63e3d0168f209e1ddd89b  debian-9.2.1-amd64-DVD-5.iso


24b56f5b79f0b6829b26f16917d7c381d92959e5e8c51091286207417dd55b1e9d54d35c8a8c5cc2daf56144c79e98f6e82339d80d12879f8c9aabeb71df8732  debian-9.2.1-amd64-DVD-5.iso
24b56f5b79f0b6829b26f16917d7c381d92959e5e8c51091286207417dd55b1e9d54d35c8a8c5cc2daf56144c79e98f6e82339d80d12879f8c9aabeb71df8732  debian-9.2.1-amd64-DVD-5.iso











jigit-mkimage
iso-image.pl
jigdump
jigsum
mkjigsnap



Template-MD5Sum=



The "isosize" program can be used to find out the
appropriate amount of bytes to be read from the optical media.

/sbin/isosize -x <device>


Then "sector count" and "sector size" are passed to "dd" to read
the appropriate amount of bytes from the optical media and the byte stream
is then piped to the appropriate checksum tool (sha512sum, sha256sum, etc).


dd if=<device> count=<sector count> bs=<sector size> | sha512sum

./check_debian_iso SHA512SUMS debian-6.0.3-amd64-netinst.iso

## Optical media verification
./check_debian_iso SHA512SUMS debian-6.0.3-amd64-DVD-1.iso /dev/dvd


xorriso for all optical media types (also doable as non-root user):
xorriso -as cdrecord -v dev=/dev/sr0 -eject debian-x.y.z-arch-MEDIUM-NN.iso


growisofs for DVD and BD optical media types:
growisofs -dvd-compat -Z /dev/sr0=debian-x.y.z-arch-MEDIUM-NN.iso


wodim for CD optical media type:
wodim -v dev=/dev/sr0 -eject -sao debian-x.y.z-arch-CD-NN.iso

create  chunks  of  4MB  each,  use
       `split  -b  4m  movie.mpeg part'



Stable images (updated for each stable release):

https://cdimage.debian.org/debian-cd/
ftp://cdimage.debian.org/debian-cd/
rsync://cdimage.debian.org/debian-cd/

Weekly images:
https://cdimage.debian.org/cdimage/weekly-builds/
ftp://cdimage.debian.org/cdimage/weekly-builds/
rsync://cdimage.debian.org/cdimage/weekly-builds/

Daily images:
https://cdimage.debian.org/cdimage/daily-builds/
ftp://cdimage.debian.org/cdimage/daily-builds/
rsync://cdimage.debian.org/cdimage/daily-builds/


jigdo-lite http://cdimage.debian.org/debian-cd/current/amd64/jigdo-dvd/debian-8.0.0-amd64-DVD-{1,2,3,4,5,6,7,8,9,10}.jigdo


jigdo-file make-image --template=debian-9.2.1-amd64-DVD-4.template --jigdo=debian-9.2.1-amd64-DVD-4.jigdo --image=debian-9.2.1-amd64-DVD-4.iso --uri Label=debian



http://cdimage.debian.org/debian-cd/7.8.0/amd64/jigdo-dvd/debian-7.8.0-amd64-DVD-{1,2,3,4,5,6,7,8,9,10}.jigdo



xorriso -as cdrecord -v dev=/dev/sr0 -eject debian-x.y.z-arch-MEDIUM-NN.iso

