#!/bin/sh


/etc/lvm/lvm.conf

>> Logical Volume Management (LVM)
>> partition type 0x8E (Linux LVM)

>> LVM uses the Linux device mapper feature (/dev/mapper)
>> A Volume Group is divided into small fixed-size chunks called Physical Extents
>> Physical Extents are mapped one-to-one to Logical Extents.
>> Logical Extents are grouped into Logical Volumes, on which filesystems are created.



■ Physical volume (PV)  A PV is a partition or a disk drive initialized to be used by LVM.
■ Physical extent (PE)  A PE is a small uniform segment of disk space. PVs are split into PEs.
■ Volume group (VG)  A VG is a storage pool, made of one or more PVs.
■ Logical extent (LE)  Every PE is associated with an LE, and these PEs can be combined into a logical volume.
■ Logical volume (LV)  An LV is a part of a VG and is made of LEs. An LV can be formatted with a filesystem and then mounted on the directory of your choice.




pvdisplay --columns
pvdisplay --maps


lvm dumpconfig



## ------------------------------------------------------------------------------------------------- ##
 • Physical volume (PV)  	## A PV is a partition or a disk drive initialized to be used by LVM.
## ------------------------------------------------------------------------------------------------- ##
 • Physical extent (PE)  	## A PE is a small uniform segment of disk space. PVs are split into PEs.
## ------------------------------------------------------------------------------------------------- ##
 • Volume group (VG)  		## A VG is a storage pool, made of one or more PVs.
## ------------------------------------------------------------------------------------------------- ##
 • Logical extent (LE)  	## Every PE is associated with an LE, 
							## and these PEs can be combined into a logical volume.
## ------------------------------------------------------------------------------------------------- ##
 • Logical volume (LV)  	## An LV is a part of a VG and is made of LEs. 
  							## An LV can be formatted with a filesystem and 
						  	## then mounted on the directory of your choice.
## ------------------------------------------------------------------------------------------------- ##



## ------------------------------------------------------------------------------------------------- ##
>> LVM uses the Linux device mapper feature (/dev/mapper)
## ------------------------------------------------------------------------------------------------- ##



## ------------------------------------------------------------------------------------------------- ##
>> A ${Volume Group} (VG) is divided into small fixed-size chunks called ${Physical Extents} (PE)
## ------------------------------------------------------------------------------------------------- ##
>> ${Physical Extents} are mapped one-to-one to ${Logical Extents} (LE)
## ------------------------------------------------------------------------------------------------- ##
>> ${Logical Extents} (LE) are grouped into ${Logical Volumes} (LV) , on which filesystems are created.
## ------------------------------------------------------------------------------------------------- ##



The physical media / partitions a hard disk, or a partition, e.g. /dev/hda, /dev/hda6 or /dev/sda. You should set the
partition types of the disk or partition to 0x8e, which is “Linux LVM”. Partitioning is done using fdisk. Please note that
your version of fdisk may not yet know this type, so it will be listed as “Unknown”. You can turn any consecutive number
of blocks on a block device into a Physical Volume:

Physical Volume (PV) a physical medium with some administrative data added to it. The command pvcreate can be used to
add the administration onto the physical medium. The command vgcreate is used to create a volume group, which consists
of one or more PV’s. A PV that has been grouped in a volume group contains Physical Extents:

Physical Extents (PE) Physical Extents are blocks of diskspace, often several megabytes in size. Using the command lvcreate
you can assign PEs to a Logical Volume:

Logical Volume (LV) A Logical Volume. On a logical volume we can use the command mkfs to get a Filesystem:



pvscan
vgscan
lvscan


lvs -o devices

lvmdiskscan


pvdisplay --columns					## 
pvdisplay --maps					## 



lvm-fullreport
lvmreport


dmeventd
dmsetup
dmstats


lvmetad


lvmconfig


The PV UUID is generated by pvcreate

pvcreate /dev/sdc4 /dev/sde			## 



vgcreate VG0 /dev/xvdf /dev/xvdg

vgdisplay
vgdisplay VG0




checks=1
verify_udev_operations=

raid_fault_policy="warn"
mirror_log_fault_policy="allocate"


backup=1
	backup_dir="/etc/lvm/backup"
verbose=1 

umask=63


metadata_read_only=0


lvmetad




lvmlockctl





dbus-uuidgen


/proc/mounts			## contains filesystem information managed by the kernel





creating and activating an LV snapshot on a CentOS distribution:
-s option denotes that an LV snapshot should be created.
-n 	name of the snapshot
-L option sets the snapshot’s size
# lvcreate -v -L 500m -s -n backup_snapshot /dev/vg00/lvol0


view the LV snapshot
lvdisplay /dev/vg00/lvol0
lvdisplay /dev/vg00/backup_snapshot

mount the LV snapshot as read-only to a temporary
location, as shown here:
# mount -o ro -t ext4 /dev/vg00/backup_snapshot Temp

umount /dev/vg00/backup_snapshot


lvremove /dev/vg00/backup_snapshot







display lvm.conf settings
lvm dumpconfig --type default







pvcreate /dev/sdc4 /dev/sde
config	___________ ## The same as lvmconfig(8) below.
devtypes __________ ## Display the recognised built-in block device types.
dumpconfig ________ ## The same as lvmconfig(8) below.
formats	 __________ ## Display recognised metadata formats.
fullreport ________ ## Report information about PVs, PV segments, VGs,  LVs  and  LV  segments, all at once.
help ______________ ## Display the help text.
lastlog	 __________ ## Display  log report of last command run in LVM shell if command log reporting is enabled.

lvpoll ____________ ## Complete lvmpolld operations (Internal command).
pvdata ____________ ## Not implemented in LVM2.
segtypes __________ ## Display recognised Logical Volume segment types.
systemid __________ ## Display any system ID currently set on this host.
tags ______________ ## Display any tags defined on this host.
version	___________ ## Display version information.




pvchange __________ ## Change attributes of a Physical Volume.
pvck ___ __________ ## Check Physical Volume metadata.
pvcreate __________ ## Initialize a disk or partition for use by LVM.
pvdisplay _________ ## Display attributes of a Physical Volume.
pvmove	 __________ ## Move Physical Extents.
pvremove __________ ## Remove a Physical Volume.
pvresize __________ ## Resize a disk or partition in use by LVM2.
pvs	_______________ ## Report information about Physical Volumes.
pvscan ____________ ## Scan all disks for Physical Volumes.
vgcfgbackup _______ ## Backup Volume Group descriptor area.
vgcfgrestore ______ ## Restore Volume Group descriptor area.
vgchange __________ ## Change attributes of a Volume Group.
vgck ______________ ## Check Volume Group metadata.
vgconvert _________ ## Convert Volume Group metadata format.
vgcreate __________ ## Create a Volume Group.
vgdisplay _________ ## Display attributes of Volume Groups.
vgexport __________ ## Make volume Groups unknown to the system.
vgextend __________ ## Add Physical Volumes to a Volume Group.
vgimport __________ ## Make exported Volume Groups known to the system.
vgimportclone _____ ## Import and rename duplicated Volume Group

vgmerge	 __________ ## Merge two Volume Groups.
vgmknodes _________ ## Recreate Volume Group directory and Logical Volume special files
vgreduce __________ ## Reduce a Volume Group by removing one or more Physical Volumes.
vgremove __________ ## Remove a Volume Group.
vgrename __________ ## Rename a Volume Group.
vgs _______________ ## Report information about Volume Groups.
vgscan ____________ ## Scan all disks for Volume Groups and rebuild caches.
vgsplit	___________ ## Split  a Volume Group into two, moving any logical volumes from one
					## Volume Group to another by moving entire Physical Volumes.

lvchange ______________ ## Change attributes of a Logical Volume.
lvconvert _____________ ## Convert a Logical Volume from linear to mirror or snapshot.
lvcreate ______________ ## Create a Logical Volume in an existing Volume Group.
lvdisplay _____________ ## Display attributes of a Logical Volume.
lvextend ______________ ## Extend the size of a Logical Volume.
lvmchange _____________ ## Change attributes of the Logical Volume Manager.
lvmconfig _____________ ## Display the configuration information after loading lvm.conf(5) and any other configuration files.
lvmdiskscan	 __________ ## Scan for all devices visible to LVM2.
lvmdump _______________ ## Create lvm2 information dumps for diagnostic purposes.
lvreduce ______________ ## Reduce the size of a Logical Volume.
lvremove ______________ ## Remove a Logical Volume.
lvrename ______________ ## Rename a Logical Volume.
lvresize ______________ ## Resize a Logical Volume.
lvs ___________________ ## Report information about Logical Volumes.
lvscan ________________ ## Scan (all disks) for Logical Volumes.

